### ISSUE TITLE
[informational] BootstrapV4 Tracking list

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#1408]
## Tasks for pending V4.0.0 release:
- Beta 3 ship list: https://github.com/twbs/bootstrap/issues/24439

### Clean up interim CSS 'fixes' which will be addresssed in V4.beta.3:
- [x] `b-modal` Remove  temporary CSS for vertically centered modal
- [x] `b-progress` Remove temporary CSS for missing transition
- [x] `b-form-file` Remove temporary CSS for focus styling, invalid/valid styling (although Firefox may still have issues, see https://github.com/twbs/bootstrap/pull/24138 & https://github.com/twbs/bootstrap/pull/24795)
- [x] `b-form-input` & `b-form-textarea` remove no longer needed `w-100` class on plaintext versions
- [ ] `b-form-checkbox` & `b-form-radio`
- - [ ] remove interim margin and rounding utility classes on button styled inputs
- - [x] New class to trigger button styles `btn-toggle-group` removing need for `data-toggle="button"` attribute. (see https://github.com/twbs/bootstrap/pull/24733). Will address issues like #1367 where people are including `bootstrap.js`
- - [x] remove attribute `data-toggle="buttons"` in button mode
- [x] `b-form-select` will use special classes for sizing: `.custom-select-sm` and `.custom-select-lg` (see https://github.com/twbs/bootstrap/pull/24699)
- [ ] `b-pagination` & `b-pagination-nav` V4.beta.3 may have a fix for active focus styling

### CSS class changes:
- [x] `b-form-select` class `.custom-select` changing to just `.form-control`, and will fully support control sizing (`sm` & `lg`), _Might be delayed until V4.beta.4_ (see https://github.com/twbs/bootstrap/issues/23058)
- [x] `b-table` class `.table-responsive` is moving back to a wrapper element. (See  https://github.com/twbs/bootstrap/pull/25058)

### Breaking changes:
- [x] input-group support for validation. removes `.input-group-addon` and rplaces with `.input-group-prepend` and `.input-group-append`.  Will require new components (possible backwards comparability may be needed).: https://github.com/twbs/bootstrap/pull/25020

### New features:
- [x] `b-modal` Vertically centered Modal
- [ ] `b-dropdown` New `dropleft` and `dropright` positions
- [x] `b-form-select` support for custom styled multiple select, single select with multiple rows (list box)

### JS behavior
- [x] `b-nav-dropdown` don't instantiate Popper.js instance. (see https://github.com/twbs/bootstrap/pull/24572 & https://github.com/twbs/bootstrap/pull/24571)
- [x] Popovers/tooltips (component and directive versions) add `boundary` option
- [x] `b-dropdown` add boundary option

### Vue.JS 2.5.x
- [x] Docs: Vue.JS has deprecated the `slot` prop in favor of the new `slot-scope`.  Docs will need to be updated to reflect this (as well as our Vue.js dependency version)

**Comment by tmorehouse** [comment]
Not a whole lot is changing in V4.beta.3 (other than mainly CSS cleanup).

Once V.beta.3 is released we can remove any temporary fix custom CSS.

**Comment by tarunmangukiya** [comment]
@tmorehouse Can you tell expected release date? (Issue with Modal Center CSS)
So I can plan whether to use temp fix or not!

Or I can create PR!

**Comment by tmorehouse** [comment]
Ye currently support vertically centered modals using custom CSS (which is the same as the proposed V4.beta.3 CSS).

Once V4.beta.3 is release by Bootstrap, we will remove the custom CSS, as V4.beta.3 wil ahve teh CSS in it (it is currently merged in twbs/bootstrap v4-dev branch.

I am not sure when Bootstrap is going to release V4.beta.3.  you will need to ask at twbs/bootstrap repo.

**Comment by tarunmangukiya** [comment]
Yes. There's a custom CSS, but it is showing scroll-bar even if the Modal is small. Like we've put 30px margin on top and bottom, which is causing the issue.

**Comment by tmorehouse** [comment]
The CSS is currently identical to Bootstrap V4-dev branch.  I wouldn't call it a bug, It is just an anomaly with the margin-top. The modal still needs to be able to handle when it is taller than the screen, which I think is why they have the margins on it.

We'll be adjusting the custom CSS as Bootstrap updates theirs.

**Comment by tmorehouse** [comment]
@tarunmangukiya version v1.4.0 has some new interim custom styling to match the new proposed V4.beta.3 styling.

**Comment by mcescalante** [comment]
FWIW as someone had asked above, v4 beta 3 was just released 3 hours ago: https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.3

**Comment by dmocho** [comment]
A breaking change of checkbox classes seems to be not on the list: custom-control-description => custom-control-label + removal of custom-control-indicator.

**Comment by toadkicker** [comment]
@dmocho I am no longer seeing custom checkboxes in bootstrap-vue

**Comment by dmocho** [comment]
My package.json contains:
`"bootstrap": "^4.0.0-beta.3",`
`"bootstrap-vue": "^1.4.0",`

When I do this:
`<b-form-checkbox v-model="removable">Removable</b-form-checkbox>`

I get this as HTML output:
`<label class="custom-control custom-checkbox">`
`  <input type="checkbox" autocomplete="off" true-value="true" class="custom-control-input" value="true" id="__BVID__87_">`
`  <span aria-hidden="true" class="custom-control-indicator"></span>`
`  <span class="custom-control-description">Removable</span>`
`</label>`

AFAIK in 4.0.0-beta.3 indicator is removed and custom-control-description became custom-control-label.
As a result of above non-plain checkboxes are no longer visible.

**Comment by toadkicker** [comment]
It also looks like bootstrap is supporting not having the label nesting the input tag as well. I'll make a PR with the updated class names but I'm not entirely sure if its requiring us to change the markup too.

**Comment by dmocho** [comment]
It's the first point in the beta.3 migration guide: https://getbootstrap.com/docs/4.0/migration/#forms.
The HTML markup and classes were changed in this release for both plain and custom checkboxes/radios.

**Comment by pi0** [comment]
#1507

Contributions to delivering beta.3 support are highly welcome :)

**Comment by KonradDeskiewicz** [comment]
I believe this one should be renamed to final as we missed beta.3 completely ;-)

**Comment by pi0** [comment]
`v2.0.0-rc.0` is released with (hopefully) a complete support for `4.0.0`.
