### ISSUE TITLE
[Informational] Bootstrap V4.beta 1, 2 & 3 ship list

### ISSUE THREAD

**Issue by tmorehouse** [bootstrap-vue/bootstrap-vue#747]
Changes / features in Bootstrap V4.beta:

V4.beta.1: https://github.com/twbs/bootstrap/issues/21568 ✔️ 
V4.beta.2: https://github.com/twbs/bootstrap/issues/23278 ✔️ 
V4.beta.3: https://github.com/twbs/bootstrap/issues/24439

We will use this issue to track progress for Bootstrap-Vue v1.0.0.x

Bootstrap-Vue components affected (we'll ad more as we find out more):
- [x] `b-tooltip` popper.js (PR #923) implemented as a directive & component
 - [x] `b-popover` popper.js (PR #923) implemented as a directive & component
 - [x] `b-badge`:
 - - [x] `b-badge` class `.badge-default` removed in beta.1
 - - [x] V4.beta.2 supports "actionable" badges (i.e. links with HREF) https://github.com/twbs/bootstrap/pull/24422
 - [ ] `b-dropdown`:
 - - [x] popper.js positioning (PR #913)
 - - [ ] Dropleft and dropright support (See https://github.com/twbs/bootstrap/pull/23860)
 - - [ ] ~Allow `container` option for dropdowns (see https://github.com/twbs/bootstrap/pull/24257)~ Canned as it breaks keyboard navigation
 - - [ ] Support for forms in dropdown (see https://github.com/twbs/bootstrap/issues/22591 and https://github.com/twbs/bootstrap/pull/22857)
 - [x] `b-nav-item-dropdown`:
 - - [x] `popper.js` - exclude positioning (see https://github.com/twbs/bootstrap/issues/23553) (PR #913)
https://github.com/twbs/bootstrap/pull/22857)
 - [x] `b-table`:
 - - [x] `b-table` renamed `.table-inverse`, `.thead-inverse`, and `.thead-default` to `.*-dark` and `.*-light`, matching BSV4 color schemes used elsewhere. See https://github.com/twbs/bootstrap/pull/23560. `b-table` docs: Bootstrap-Vue already supports any variant name on b-table, but needs updated documentation when V4.beta.2 ships. (PR #1222)
 - - [x] `b-table`: table-responsive breakpoints: Responsive tables generate classes for each grid breakpoint, meaning they have added `.table-responsive-{sm,md,lg,xl}` to the already present `.table-responsive`.. See https://github.com/twbs/bootstrap/pull/22804. (PR #1222)
 - [x] `b-card` Background variants & color classes
 - [x] `b-navbar` & `b-nav-toggle` Class changes (commit 1fab0338250199a3229c80a4ae24459d49677c1d)
 - [x] `b-pagination` changes to `.hidden-*` class names to `.d-*`  (PR #840)
  - [x] `b-progress`:
 - - [x] `b-progress` height controls (PR #837)
 - - [x] `b-progress` V4.beta.2 changes how height is applied https://github.com/twbs/bootstrap/pull/22703 (PR #1217)
 - - [x] `b-progress` transition changes
 - - [x] `b-progress` multiple progress bar support (PR #889) 
 - [x] `b-carousel` transition timings, tweaks (fixed in PR #809, and more)
 - [x] `b-modal`
 - - [x] changes to scroll bar measuring and padding adjustments for better BSV4 alignment, (PR #1024)
 - - [x] `b-modal` V4.beta.3 will introduce a modal vertical center option (see https://github.com/twbs/bootstrap/pull/24510) (PR #1246 , but will need a revisit once BSV4.beta.3 is released)
  - [x] `b-button`, `b-form-radio`, `b-form-checkbox` Toggle buttons don't honor [disabled] or .disabled (this is actually fixed in Bootstrap-Vue  :smile: )
 - [x] `b-col`
 - - [x] new component (PR #836)
 - - [x] bring back `offset-*` classes (PR #929)
 - - [x] Document offset prop for `b-col`
 - [ ] `b-collapse` use show/flexshow based on collapse flexbox (see https://github.com/twbs/bootstrap/pull/22758) (on hold until BS V4.beta.3)
 - [ ] `b-form-input` & `b-form-textarea` readonly plaintext style missing 100% width styles. which will be fixed in BS V4.beta.3. Will need to remove the `w-100` class addition when beta.3 is released.
 - [ ] Forms: V4.beta has major form validation changes compared to v4.alpha.6. Only two new validation states now: `valid` and `invalid` (`warning` has been removed). Now supports native browser validation states as well.  **Note: there are known issues & limitations using the new BS 4.beta form validation contextual states with wrapped input elements.** (see https://github.com/twbs/bootstrap/issues/23454)
 - - [x] `b-form` validation classes and attributes + native browser validation (PR #847)
 - - [x] `b-form-group` Validation states no longer applied at the root fieldset (was `b-form-fieldset`)  (PR #847)
 - - [x] `b-form-file` Now accepts validation states + native states (PR #847)
 - - [x] `b-form-file` new classes for plain file inputs + native states (PR #847)
 - - [x] `b-form-input` new validation classes + native states (PR #847)
 - - [x] `b-form-select` new validation classes + native states (PR #847)
   - - [x] 'b-form-select': custom-select with "multiple" will be supported in BSV4.beta.2 (PR #1223)
   - - [ ] 'b-form-select': `select.custom-select` class will be changing to `select.form-control` class in V4.beta.3
   - - [ ] 'b-form-select': will properly support sizing in V4.beta.3
 - - [x] `b-form-radio` new validation classes + native states (PR #847)
 - - [x] `b-form-checkbox` new validation classes + native states (PR #847)
 - - [x] `b-form-radio` & `b-form-checkbox`: Slight markup changes needed for BSV4.beta.3 for styling (see https://github.com/twbs/bootstrap/pull/23444) (PR #1253, may need to revisit once BSV4.beta.3 released)
 - - [x] `b-form-input-static` new class name (PR #847)
 - - [x] `b-form-text` (new component) help block text (PR #846,#847)
 - - [x] `b-form-feedback` (new component & new class) feedback text (PR #847)
 - - [x] `b-form-row` (new component) helper for inline forms (PR #844, #847)
 - - [x] Updated form component docs
 - - [x] Rework how `b-form-select`, `b-form-radio`, and `b-form-checkbox` work, using sub-components. Allow `optgroup` in `form-select` (PR #994)
 - - [ ] Need more information on when invalid/valid sates can be applied to `form-group`, etc

Directives that will need changes:
 - [ ] ~`v-b-scrollspy` changes in which classes can be active (for more than just navs)~ not implemented in BS4.beta yet
 - [x] `v-b-toggle` Collapse support multi target (already available in Bootstrap-Vue :smile: )

**Comment by alexsasharegan** [comment]
I knew something was up with the grid system! That col component is gonna need an overhaul.

**Comment by ImTheDeveloper** [comment]
I think it would be great if you could link out to the relevant bootstrap 4 docs where things like "variant" and "type" translate over to a specific option in bootstrap. I've found I'm often having to go to your docs, then to the underlying component source code to view the "defaults" and then over to the official bootstrap docs to see what options I can pass in.

Example of this is the navbar which has "variant" and "type" as options. These form part of:
https://v4-alpha.getbootstrap.com/components/navbar/#color-schemes
https://v4-alpha.getbootstrap.com/utilities/colors/#content

**Comment by tmorehouse** [comment]
@ImTheDeveloper We've started to include supported variants in many of the component docs in the 1.x banch (and at the v1.0.0.beta docs at https://bootstrap-vue.now.sh/docs/)

**Comment by tmorehouse** [comment]
Bootstrap V4.0.0.beta.2 shiplist: https://github.com/twbs/bootstrap/issues/23278

**Comment by slakbal** [comment]
hey there, does this mean that bootstrap-vue supports  v4.0.0-beta.2?

**Comment by tmorehouse** [comment]
Not yet, as bootstrap beta.2 hasn't shipped yet.  There have been some changes that will support the upcoming V4.beta.2 release, but there are a few things that are still up in the air with V4.beta.2, and will need to be handled when V4.beta.2 is officially released.

**Comment by mosinve** [comment]
@tmorehouse ,  V4.beta.2 is already officially released https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.2

**Comment by tmorehouse** [comment]
Just saw that :-)

Will need to go through and see what else has changed.
